server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/comate?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
